// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpclib

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CryptoServiceClient is the client API for CryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoServiceClient interface {
	SSMEncrypt(ctx context.Context, in *CryptoRequest, opts ...grpc.CallOption) (*SSMReply, error)
	SSMDecrypt(ctx context.Context, in *CryptoRequest, opts ...grpc.CallOption) (*SSMReply, error)
	SSMGetRandom(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*SSMReply, error)
	SSMPing(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SSMReply, error)
}

type cryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoServiceClient(cc grpc.ClientConnInterface) CryptoServiceClient {
	return &cryptoServiceClient{cc}
}

func (c *cryptoServiceClient) SSMEncrypt(ctx context.Context, in *CryptoRequest, opts ...grpc.CallOption) (*SSMReply, error) {
	out := new(SSMReply)
	err := c.cc.Invoke(ctx, "/grpclib.CryptoService/SSMEncrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) SSMDecrypt(ctx context.Context, in *CryptoRequest, opts ...grpc.CallOption) (*SSMReply, error) {
	out := new(SSMReply)
	err := c.cc.Invoke(ctx, "/grpclib.CryptoService/SSMDecrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) SSMGetRandom(ctx context.Context, in *RandomRequest, opts ...grpc.CallOption) (*SSMReply, error) {
	out := new(SSMReply)
	err := c.cc.Invoke(ctx, "/grpclib.CryptoService/SSMGetRandom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) SSMPing(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SSMReply, error) {
	out := new(SSMReply)
	err := c.cc.Invoke(ctx, "/grpclib.CryptoService/SSMPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServiceServer is the server API for CryptoService service.
// All implementations must embed UnimplementedCryptoServiceServer
// for forward compatibility
type CryptoServiceServer interface {
	SSMEncrypt(context.Context, *CryptoRequest) (*SSMReply, error)
	SSMDecrypt(context.Context, *CryptoRequest) (*SSMReply, error)
	SSMGetRandom(context.Context, *RandomRequest) (*SSMReply, error)
	SSMPing(context.Context, *EmptyRequest) (*SSMReply, error)
	mustEmbedUnimplementedCryptoServiceServer()
}

// UnimplementedCryptoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoServiceServer struct {
}

func (UnimplementedCryptoServiceServer) SSMEncrypt(context.Context, *CryptoRequest) (*SSMReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSMEncrypt not implemented")
}
func (UnimplementedCryptoServiceServer) SSMDecrypt(context.Context, *CryptoRequest) (*SSMReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSMDecrypt not implemented")
}
func (UnimplementedCryptoServiceServer) SSMGetRandom(context.Context, *RandomRequest) (*SSMReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSMGetRandom not implemented")
}
func (UnimplementedCryptoServiceServer) SSMPing(context.Context, *EmptyRequest) (*SSMReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SSMPing not implemented")
}
func (UnimplementedCryptoServiceServer) mustEmbedUnimplementedCryptoServiceServer() {}

// UnsafeCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoServiceServer will
// result in compilation errors.
type UnsafeCryptoServiceServer interface {
	mustEmbedUnimplementedCryptoServiceServer()
}

func RegisterCryptoServiceServer(s grpc.ServiceRegistrar, srv CryptoServiceServer) {
	s.RegisterService(&CryptoService_ServiceDesc, srv)
}

func _CryptoService_SSMEncrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).SSMEncrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpclib.CryptoService/SSMEncrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).SSMEncrypt(ctx, req.(*CryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_SSMDecrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).SSMDecrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpclib.CryptoService/SSMDecrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).SSMDecrypt(ctx, req.(*CryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_SSMGetRandom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).SSMGetRandom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpclib.CryptoService/SSMGetRandom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).SSMGetRandom(ctx, req.(*RandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_SSMPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).SSMPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpclib.CryptoService/SSMPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).SSMPing(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoService_ServiceDesc is the grpc.ServiceDesc for CryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpclib.CryptoService",
	HandlerType: (*CryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SSMEncrypt",
			Handler:    _CryptoService_SSMEncrypt_Handler,
		},
		{
			MethodName: "SSMDecrypt",
			Handler:    _CryptoService_SSMDecrypt_Handler,
		},
		{
			MethodName: "SSMGetRandom",
			Handler:    _CryptoService_SSMGetRandom_Handler,
		},
		{
			MethodName: "SSMPing",
			Handler:    _CryptoService_SSMPing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpclib/cryptoService.proto",
}
